### ISSUE TITLE
WARNING: Unable to resolve link target: aicompressionsaas.qmd

### ISSUE THREAD

**Issue by doyu** [ninjalabo/ninjalabo.github.io#4]
![image](https://github.com/user-attachments/assets/5cb2d173-9d53-4bbf-9fda-14250c054d90)

Any idea?

**Comment by nghivo94** [comment]
It is this part that is causing the issue.
![image](https://github.com/user-attachments/assets/17717f54-8002-4595-b940-dfd07fe8feb8)

If you add a new blog under `blogs/` directory, it will be automatically rendered to this format:
![image](https://github.com/user-attachments/assets/24d8129c-4a39-4f7c-87c7-4d78b8070d0e)

While the previous part will render to this format:
![image](https://github.com/user-attachments/assets/f71e7e77-4f33-43ba-83d9-b8b69c44cffe)

So to fix this issue, you can either remove that part or add the `blogs/` prefix to the file links, e.g., `tinymlaas.qmd` to `blogs/tinymlaas.qmd`
